encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry>", views.entry, name="entry"),
    path("edit/<str:entry>", views.edit, name="edit"),
    path("Newpage", views.Newpage, name="Newpage"),
    path("search", views.search, name="search"),
    path("random", views.rand, name="rand"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("encyclopedia.urls")),
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django import forms
import random
from markdown2 import markdown
from . import util


# form to edit old pages/entries
class editForm(forms.Form):
    title = forms.CharField(label="Title", required=True)
    body = forms.CharField(label="Body", required=True, widget=forms.Textarea())


# Searchbar
class searchForm(forms.Form):
    search = forms.CharField(required=True)


# form To make new pages/enteries
class ADDpageForm(forms.Form):
    title = forms.CharField(label="Enter Title", required=True)
    body = forms.CharField(label="Enter Body", required=True, widget=forms.Textarea())


searchbar = searchForm()
newpage = ADDpageForm()
editpage = editForm()


# index
def index(request):
    return render(
        request,
        "encyclopedia/index.html",
        {"entries": util.list_entries(), "form": searchbar},
    )


# to view selected page or page entered in url
def entry(request, entry):
    page = util.get_entry(entry)
    if page is None:
        return render(
            request, "encyclopedia/page is not available.html", {"form": searchbar}
        )
    else:
        Body = markdown(page)
        return render(
            request,
            "encyclopedia/entry.html",
            {"title": entry, "Body": Body, "form": searchbar},
        )


# search function
def search(request):
    searchbar = searchForm(request.POST)
    searchbar.is_valid()
    data = searchbar.cleaned_data.get("search")
    Page = False
    for entry in util.list_entries():
        if data.upper() == entry.upper():
            Entry = util.get_entry(data)
            Body = markdown(Entry)
            Page = True
            break
    # if page/entry found load encyclopedia/entry.html
    if Page:
        return render(
            request,
            "encyclopedia/entry.html",
            {"Body": Body, "form": searchbar, "title": data},
        )
        # checking substring
        # MS = matching substring
    else:
        MS = []
        for entry in util.list_entries():
            if data.upper() in entry.upper():
                MS.append(entry)

        # list of entries with substring on index
        if len(MS) != 0:
            return render(
                request,
                "encyclopedia/index.html",
                {"entries": MS, "form": searchbar},
            )

        # if no match load page is not available template
        else:
            return render(
                request,
                "encyclopedia/page is not available.html",
                {"form": searchbar},
            )


# view to create new pages/entries
def Newpage(request):
    # if accesed using POST
    if request.method == "POST":
        newpage = ADDpageForm(request.POST)
        if newpage.is_valid():
            # getting title and body data
            title = newpage.cleaned_data["title"]
            body = newpage.cleaned_data["body"]
            present = False
            for entry in util.list_entries():
                if title == entry:
                    present = True
                    break
            if present:
                return render(
                    request,
                    "encyclopedia/page already exists.html",
                    {"form": searchbar},
                )
            else:
                util.save_entry(title, body)
                page = util.get_entry(title)
                Body = markdown(page)
                return render(
                    request,
                    "encyclopedia/entry.html",
                    {"title": title, "Body": Body, "form": searchbar},
                )
    # if accesed using GET
    else:
        newpage = ADDpageForm()
        return render(
            request,
            "encyclopedia/Newpage.html",
            {"form": searchbar, "newpage": newpage},
        )


# Edit selected page/entry
def edit(request, entry):
    if request.method == "POST":
        editpage = editForm(request.POST)
        if editpage.is_valid():
            entry = editpage.cleaned_data["title"]
            body = editpage.cleaned_data["body"]
            # saving Body using save_entry funcyion in util.py
            util.save_entry(entry, body)
            Body = markdown(body)
            return render(
                request,
                "encyclopedia/entry.html",
                {"title": entry, "Body": Body, "form": searchbar},
            )
    else:
        editpage = editForm({"title": entry, "body": util.get_entry(entry)})
        return render(
            request, "encyclopedia/edit.html", {"form": searchbar, "editform": editpage}
        )


# random page button
def rand(request):
    entrieslist = util.list_entries()
    Length = len(entrieslist)
    # genetrating random index number to choose a random fie from a list of entries
    Index = random.randint(0, Length - 1)
    title = entrieslist[Index]
    page = util.get_entry(title)
    Body = markdown(page)
    return render(
        request,
        "encyclopedia/rand.html",
        {"form": searchbar, "title": title, "Body": Body},
    )

encyclopedia/templates/encyclopedia/Newpage.html
{% extends "encyclopedia/layout.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Search
{% endblock %}

{% block body %}
        <form action="{% url 'encyclopedia:Newpage' %}" method="POST">
            {% csrf_token %}
            {{newpage|crispy}}
            <input type="Submit" name="submit" value="Submit"/>
        </form>
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Edit
{% endblock %}

{% block body %}
        <form action="{% url 'encyclopedia:edit' entry=editform.data.title %}" method="POST">
            {% csrf_token %}
            {{editform|crispy}}
            <input type="Submit" name="submit" value="Submit"/>
        </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
<a href="{% url 'encyclopedia:edit' title %}">Edit Page</a>
        {{ Body | safe }}
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>
    <ul>
        {% for entry in entries %}
        <a href="/wiki/{{entry}}"><li>{{ entry }}</li></a>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="POST">
                    {% csrf_token %}
                    {{form}}
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:Newpage' %}">ADD New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:rand' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/page already exists.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    ERROR
{% endblock %}

{% block body %}
    <h1>ERROR</h1>
    <h3>Page already exists</h3>

    <pre>
        try to search the page 
    </pre>

{% endblock %}

encyclopedia/templates/encyclopedia/page is not available.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    ERROR
{% endblock %}

{% block body %}
    <h1>ERROR</h1>
    <h3>Page is not available</h3>

    <pre>
        create new page if you want to
    </pre>

{% endblock %}

encyclopedia/templates/encyclopedia/rand.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <a href="edit/{{title}}">Edit Page</a>
        {{ Body | safe }}
{% endblock %}